FROM node:20-slim

WORKDIR /app

RUN apt-get update && apt-get install -y openssl

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

EXPOSE 8081

CMD [ "pnpm" , "dev:docker" ]
